// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technology_tp1.Models;

namespace technology_tp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190929214511_added_constraints_itemimage")]
    partial class added_constraints_itemimage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("technology_tp1.Models.DeliveryMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeactivated");

                    b.Property<bool>("IsEmployed");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Mary Smith",
                            Phone = "270-128-63261"
                        },
                        new
                        {
                            Id = -2,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Michelle Harrison",
                            Phone = "469-464-53200"
                        },
                        new
                        {
                            Id = -3,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Mary Burrows",
                            Phone = "166-666-12885"
                        },
                        new
                        {
                            Id = -4,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "John Clarkson",
                            Phone = "769-651-91027"
                        },
                        new
                        {
                            Id = -5,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Barbara Dent",
                            Phone = "317-144-28073"
                        },
                        new
                        {
                            Id = -6,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Marcus Anderson",
                            Phone = "718-023-68092"
                        },
                        new
                        {
                            Id = -7,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Felicity Yorke",
                            Phone = "321-554-93065"
                        },
                        new
                        {
                            Id = -8,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Victoria Davis",
                            Phone = "885-045-48886"
                        },
                        new
                        {
                            Id = -9,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Betty Davis",
                            Phone = "965-031-15058"
                        },
                        new
                        {
                            Id = -10,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Eve Peterson",
                            Phone = "569-813-95839"
                        },
                        new
                        {
                            Id = -11,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Matthew Washington",
                            Phone = "232-878-29507"
                        },
                        new
                        {
                            Id = -12,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Judith Peters",
                            Phone = "855-139-37980"
                        },
                        new
                        {
                            Id = -13,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Margaret Jones",
                            Phone = "779-034-50682"
                        },
                        new
                        {
                            Id = -14,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Philip Johnson",
                            Phone = "040-253-81398"
                        },
                        new
                        {
                            Id = -15,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Terry Peterson",
                            Phone = "762-139-34112"
                        },
                        new
                        {
                            Id = -16,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Eve Andrews",
                            Phone = "200-586-04018"
                        },
                        new
                        {
                            Id = -17,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Carol Kirby",
                            Phone = "930-906-41457"
                        },
                        new
                        {
                            Id = -18,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Alison Harrison",
                            Phone = "798-268-56107"
                        },
                        new
                        {
                            Id = -19,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Adam Jones",
                            Phone = "372-628-59347"
                        },
                        new
                        {
                            Id = -20,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Anna Brown",
                            Phone = "614-639-72464"
                        },
                        new
                        {
                            Id = -21,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Sandra Hall",
                            Phone = "321-919-62742"
                        },
                        new
                        {
                            Id = -22,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Sharon Washington",
                            Phone = "086-045-85655"
                        },
                        new
                        {
                            Id = -23,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Ann Stevens",
                            Phone = "151-905-66829"
                        },
                        new
                        {
                            Id = -24,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Charlotte Clarke",
                            Phone = "824-565-09375"
                        },
                        new
                        {
                            Id = -25,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Helen Miller",
                            Phone = "382-926-85833"
                        },
                        new
                        {
                            Id = -26,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Ruth Kirby",
                            Phone = "513-462-12421"
                        },
                        new
                        {
                            Id = -27,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Charlotte Johnson",
                            Phone = "812-280-76840"
                        },
                        new
                        {
                            Id = -28,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Charlotte Garcia",
                            Phone = "321-924-20732"
                        },
                        new
                        {
                            Id = -29,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Michelle Clark",
                            Phone = "013-442-85938"
                        },
                        new
                        {
                            Id = -30,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "William Miller",
                            Phone = "550-188-58905"
                        },
                        new
                        {
                            Id = -31,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Tabitha Lewis",
                            Phone = "499-749-31705"
                        },
                        new
                        {
                            Id = -32,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Joseph Hall",
                            Phone = "981-177-56824"
                        },
                        new
                        {
                            Id = -33,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Herbert Walker",
                            Phone = "136-499-57562"
                        },
                        new
                        {
                            Id = -34,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Adam Harris",
                            Phone = "142-607-93188"
                        },
                        new
                        {
                            Id = -35,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Joseph Williams",
                            Phone = "697-891-16534"
                        },
                        new
                        {
                            Id = -36,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Jennifer Lewis",
                            Phone = "326-510-97312"
                        },
                        new
                        {
                            Id = -37,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Mark Baker",
                            Phone = "631-502-65129"
                        },
                        new
                        {
                            Id = -38,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Diana Moore",
                            Phone = "639-646-66396"
                        },
                        new
                        {
                            Id = -39,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Paul Peters",
                            Phone = "170-570-90337"
                        },
                        new
                        {
                            Id = -40,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Dorothy Clark",
                            Phone = "224-648-08140"
                        },
                        new
                        {
                            Id = -41,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Maria Jeffries",
                            Phone = "918-402-72557"
                        },
                        new
                        {
                            Id = -42,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Dorothy Rodriguez",
                            Phone = "803-263-87271"
                        },
                        new
                        {
                            Id = -43,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Alison Peters",
                            Phone = "213-945-91285"
                        },
                        new
                        {
                            Id = -44,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Anne Peterson",
                            Phone = "545-459-45001"
                        },
                        new
                        {
                            Id = -45,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Margaret Thatcher",
                            Phone = "391-836-05829"
                        },
                        new
                        {
                            Id = -46,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Hugh Brown",
                            Phone = "387-527-34477"
                        },
                        new
                        {
                            Id = -47,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "William Garcia",
                            Phone = "134-445-81705"
                        },
                        new
                        {
                            Id = -48,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Cheryl Miller",
                            Phone = "041-972-69409"
                        },
                        new
                        {
                            Id = -49,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Beryl Lewis",
                            Phone = "075-606-46954"
                        });
                });

            modelBuilder.Entity("technology_tp1.Models.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Full")
                        .IsRequired();

                    b.Property<byte[]>("Medium")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<byte[]>("Small")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("technology_tp1.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId");

                    b.Property<string>("Nom");

                    b.Property<double>("Prix");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("technology_tp1.Models.MenuItem", b =>
                {
                    b.HasOne("technology_tp1.Models.ItemImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
