// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technology_tp1.Models;

namespace technology_tp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190929213143_added_name_itemimage")]
    partial class added_name_itemimage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("technology_tp1.Models.DeliveryMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeactivated");

                    b.Property<bool>("IsEmployed");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Donald Harris",
                            Phone = "228-011-12112"
                        },
                        new
                        {
                            Id = -2,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Felicity Thompson",
                            Phone = "266-739-30257"
                        },
                        new
                        {
                            Id = -3,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Lisa Taylor",
                            Phone = "534-626-58820"
                        },
                        new
                        {
                            Id = -4,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Sharon Moore",
                            Phone = "966-651-27839"
                        },
                        new
                        {
                            Id = -5,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Helena Jones",
                            Phone = "556-358-38027"
                        },
                        new
                        {
                            Id = -6,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Jessica Edwards",
                            Phone = "361-660-99063"
                        },
                        new
                        {
                            Id = -7,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Elizabeth Harris",
                            Phone = "493-474-93375"
                        },
                        new
                        {
                            Id = -8,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Fiona Smythe",
                            Phone = "343-503-09736"
                        },
                        new
                        {
                            Id = -9,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Mary Davies",
                            Phone = "275-787-43774"
                        },
                        new
                        {
                            Id = -10,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Sharon Baker",
                            Phone = "235-228-29303"
                        },
                        new
                        {
                            Id = -11,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Anna Baker",
                            Phone = "736-047-38509"
                        },
                        new
                        {
                            Id = -12,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Robyn Lee",
                            Phone = "010-612-12330"
                        },
                        new
                        {
                            Id = -13,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Paul Lake",
                            Phone = "782-691-67339"
                        },
                        new
                        {
                            Id = -14,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Edward Jackson",
                            Phone = "771-701-89986"
                        },
                        new
                        {
                            Id = -15,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Richard Kirby",
                            Phone = "911-920-78844"
                        },
                        new
                        {
                            Id = -16,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Fiona Clarkson",
                            Phone = "719-052-54638"
                        },
                        new
                        {
                            Id = -17,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Ronald Harrison",
                            Phone = "039-938-40029"
                        },
                        new
                        {
                            Id = -18,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "George Martinez",
                            Phone = "715-714-02213"
                        },
                        new
                        {
                            Id = -19,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Mark Hall",
                            Phone = "140-431-47032"
                        },
                        new
                        {
                            Id = -20,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Nancy Lewis",
                            Phone = "420-167-35789"
                        },
                        new
                        {
                            Id = -21,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Patricia Wilson",
                            Phone = "104-715-89942"
                        },
                        new
                        {
                            Id = -22,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Helen Thatcher",
                            Phone = "315-671-63067"
                        },
                        new
                        {
                            Id = -23,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Kevin Johnson",
                            Phone = "060-022-61505"
                        },
                        new
                        {
                            Id = -24,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Mark Harris",
                            Phone = "281-847-41975"
                        },
                        new
                        {
                            Id = -25,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Charles Jefferson",
                            Phone = "753-536-34256"
                        },
                        new
                        {
                            Id = -26,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Maria Davies",
                            Phone = "946-638-64065"
                        },
                        new
                        {
                            Id = -27,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Edward Peters",
                            Phone = "530-130-85279"
                        },
                        new
                        {
                            Id = -28,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Elizabeth Smythe",
                            Phone = "844-780-07750"
                        },
                        new
                        {
                            Id = -29,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Simon Stevens",
                            Phone = "031-593-88310"
                        },
                        new
                        {
                            Id = -30,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Terry Jeffries",
                            Phone = "461-280-03465"
                        },
                        new
                        {
                            Id = -31,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Kevin Edwards",
                            Phone = "967-466-24349"
                        },
                        new
                        {
                            Id = -32,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Kevin Thatcher",
                            Phone = "167-313-99079"
                        },
                        new
                        {
                            Id = -33,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Sharon Johnson",
                            Phone = "762-024-19272"
                        },
                        new
                        {
                            Id = -34,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Sharon Walker",
                            Phone = "497-549-78499"
                        },
                        new
                        {
                            Id = -35,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Nancy Robinson",
                            Phone = "645-863-30349"
                        },
                        new
                        {
                            Id = -36,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Lucy Thompson",
                            Phone = "111-129-22440"
                        },
                        new
                        {
                            Id = -37,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Carol Hall",
                            Phone = "752-417-69250"
                        },
                        new
                        {
                            Id = -38,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Charles Lake",
                            Phone = "322-577-55473"
                        },
                        new
                        {
                            Id = -39,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Herbert Major",
                            Phone = "568-964-30414"
                        },
                        new
                        {
                            Id = -40,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Linda Davidson",
                            Phone = "080-817-41352"
                        },
                        new
                        {
                            Id = -41,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Nancy Taylor",
                            Phone = "555-694-14409"
                        },
                        new
                        {
                            Id = -42,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Jessica Hall",
                            Phone = "569-274-12281"
                        },
                        new
                        {
                            Id = -43,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "James Johnson",
                            Phone = "453-669-71679"
                        },
                        new
                        {
                            Id = -44,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Sandra Davidson",
                            Phone = "667-005-05933"
                        },
                        new
                        {
                            Id = -45,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Ronald Taylor",
                            Phone = "069-054-82838"
                        },
                        new
                        {
                            Id = -46,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Kenneth Thatcher",
                            Phone = "054-015-74484"
                        },
                        new
                        {
                            Id = -47,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Edward Garcia",
                            Phone = "743-762-46278"
                        },
                        new
                        {
                            Id = -48,
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Mary Clarkson",
                            Phone = "079-138-72623"
                        },
                        new
                        {
                            Id = -49,
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Beryl Clark",
                            Phone = "349-564-15855"
                        });
                });

            modelBuilder.Entity("technology_tp1.Models.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Full");

                    b.Property<byte[]>("Medium");

                    b.Property<string>("Name");

                    b.Property<byte[]>("Small");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("technology_tp1.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId");

                    b.Property<string>("Nom");

                    b.Property<double>("Prix");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("technology_tp1.Models.MenuItem", b =>
                {
                    b.HasOne("technology_tp1.Models.ItemImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
