// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technology_tp1.Models;

namespace technology_tp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190929160626_added_isemployed")]
    partial class added_isemployed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("technology_tp1.Models.DeliveryMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEmployed");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsEmployed = false,
                            Name = "Ruth Robinson",
                            Phone = "593-185-95826"
                        },
                        new
                        {
                            Id = -2,
                            IsEmployed = false,
                            Name = "John Major",
                            Phone = "952-726-55658"
                        },
                        new
                        {
                            Id = -3,
                            IsEmployed = false,
                            Name = "Richard Brown",
                            Phone = "612-306-18158"
                        },
                        new
                        {
                            Id = -4,
                            IsEmployed = false,
                            Name = "Betty Jeffries",
                            Phone = "747-211-09509"
                        },
                        new
                        {
                            Id = -5,
                            IsEmployed = true,
                            Name = "Laura Williams",
                            Phone = "557-754-89498"
                        },
                        new
                        {
                            Id = -6,
                            IsEmployed = false,
                            Name = "Daniel Jackson",
                            Phone = "194-274-31596"
                        },
                        new
                        {
                            Id = -7,
                            IsEmployed = false,
                            Name = "Dorothy Brown",
                            Phone = "142-202-68599"
                        },
                        new
                        {
                            Id = -8,
                            IsEmployed = false,
                            Name = "Donald Jackson",
                            Phone = "397-299-04742"
                        },
                        new
                        {
                            Id = -9,
                            IsEmployed = false,
                            Name = "Richard Washington",
                            Phone = "216-374-48114"
                        },
                        new
                        {
                            Id = -10,
                            IsEmployed = true,
                            Name = "Dorothy Stevens",
                            Phone = "908-266-44311"
                        },
                        new
                        {
                            Id = -11,
                            IsEmployed = false,
                            Name = "Nancy Stevens",
                            Phone = "840-678-88498"
                        },
                        new
                        {
                            Id = -12,
                            IsEmployed = true,
                            Name = "Barbara Jones",
                            Phone = "811-951-50127"
                        },
                        new
                        {
                            Id = -13,
                            IsEmployed = false,
                            Name = "Edgar Moore",
                            Phone = "490-329-02591"
                        },
                        new
                        {
                            Id = -14,
                            IsEmployed = false,
                            Name = "Edgar Robertson",
                            Phone = "583-929-75262"
                        },
                        new
                        {
                            Id = -15,
                            IsEmployed = true,
                            Name = "Helen Wilson",
                            Phone = "056-759-02847"
                        },
                        new
                        {
                            Id = -16,
                            IsEmployed = false,
                            Name = "Victoria Harris",
                            Phone = "907-479-43966"
                        },
                        new
                        {
                            Id = -17,
                            IsEmployed = true,
                            Name = "Maria Anderson",
                            Phone = "518-595-56784"
                        },
                        new
                        {
                            Id = -18,
                            IsEmployed = false,
                            Name = "James Kirby",
                            Phone = "015-871-74705"
                        },
                        new
                        {
                            Id = -19,
                            IsEmployed = false,
                            Name = "Betty Thomas",
                            Phone = "426-796-10073"
                        },
                        new
                        {
                            Id = -20,
                            IsEmployed = true,
                            Name = "Mark Dent",
                            Phone = "499-564-89988"
                        },
                        new
                        {
                            Id = -21,
                            IsEmployed = false,
                            Name = "Joseph Harrison",
                            Phone = "395-832-97588"
                        },
                        new
                        {
                            Id = -22,
                            IsEmployed = false,
                            Name = "Betty Harrison",
                            Phone = "768-466-31436"
                        },
                        new
                        {
                            Id = -23,
                            IsEmployed = false,
                            Name = "Ursula Brown",
                            Phone = "804-634-81305"
                        },
                        new
                        {
                            Id = -24,
                            IsEmployed = true,
                            Name = "Mark Thatcher",
                            Phone = "328-501-96970"
                        },
                        new
                        {
                            Id = -25,
                            IsEmployed = true,
                            Name = "Jason Peters",
                            Phone = "927-497-69799"
                        },
                        new
                        {
                            Id = -26,
                            IsEmployed = false,
                            Name = "James Clark",
                            Phone = "394-503-40899"
                        },
                        new
                        {
                            Id = -27,
                            IsEmployed = false,
                            Name = "Ursula Harris",
                            Phone = "576-602-59606"
                        },
                        new
                        {
                            Id = -28,
                            IsEmployed = false,
                            Name = "Marcus Clarke",
                            Phone = "641-731-35335"
                        },
                        new
                        {
                            Id = -29,
                            IsEmployed = true,
                            Name = "Jessica Abel",
                            Phone = "309-331-88488"
                        },
                        new
                        {
                            Id = -30,
                            IsEmployed = false,
                            Name = "Kimberly Kirby",
                            Phone = "924-735-28622"
                        },
                        new
                        {
                            Id = -31,
                            IsEmployed = true,
                            Name = "Edwin Jefferson",
                            Phone = "164-675-47298"
                        },
                        new
                        {
                            Id = -32,
                            IsEmployed = false,
                            Name = "Susan Jefferson",
                            Phone = "149-933-61141"
                        },
                        new
                        {
                            Id = -33,
                            IsEmployed = true,
                            Name = "Daniel Clark",
                            Phone = "045-072-51895"
                        },
                        new
                        {
                            Id = -34,
                            IsEmployed = true,
                            Name = "Richard Kirby",
                            Phone = "948-207-14914"
                        },
                        new
                        {
                            Id = -35,
                            IsEmployed = false,
                            Name = "David Martin",
                            Phone = "205-093-07116"
                        },
                        new
                        {
                            Id = -36,
                            IsEmployed = false,
                            Name = "William Robinson",
                            Phone = "743-646-31038"
                        },
                        new
                        {
                            Id = -37,
                            IsEmployed = true,
                            Name = "Tabitha Grant",
                            Phone = "719-265-01819"
                        },
                        new
                        {
                            Id = -38,
                            IsEmployed = true,
                            Name = "Ann Kirby",
                            Phone = "404-230-16798"
                        },
                        new
                        {
                            Id = -39,
                            IsEmployed = false,
                            Name = "Michael Burrows",
                            Phone = "257-844-39326"
                        },
                        new
                        {
                            Id = -40,
                            IsEmployed = true,
                            Name = "Laura Martin",
                            Phone = "960-698-62525"
                        },
                        new
                        {
                            Id = -41,
                            IsEmployed = false,
                            Name = "Harold Smythe",
                            Phone = "554-783-98600"
                        },
                        new
                        {
                            Id = -42,
                            IsEmployed = false,
                            Name = "Anthony Peterson",
                            Phone = "760-192-88735"
                        },
                        new
                        {
                            Id = -43,
                            IsEmployed = true,
                            Name = "Kevin Thatcher",
                            Phone = "815-560-88619"
                        },
                        new
                        {
                            Id = -44,
                            IsEmployed = true,
                            Name = "Kevin Washington",
                            Phone = "652-859-50357"
                        },
                        new
                        {
                            Id = -45,
                            IsEmployed = true,
                            Name = "Helen Hall",
                            Phone = "172-729-55368"
                        },
                        new
                        {
                            Id = -46,
                            IsEmployed = false,
                            Name = "William Anthony",
                            Phone = "432-760-03982"
                        },
                        new
                        {
                            Id = -47,
                            IsEmployed = true,
                            Name = "Terry Williams",
                            Phone = "314-302-57391"
                        },
                        new
                        {
                            Id = -48,
                            IsEmployed = false,
                            Name = "Diana Robertson",
                            Phone = "110-213-59720"
                        },
                        new
                        {
                            Id = -49,
                            IsEmployed = true,
                            Name = "Steven Washington",
                            Phone = "836-427-40989"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
